import type { Metadata } from "next";
import { Bricolage_Grotesque, Geist } from "next/font/google";
import "@/sass/main.scss";

import { headers } from "next/headers";

import Header from "./components/Header";

export const metadata: Metadata = {
  title: "APDSN",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathName = headersList.get("x-current");
  const className = pathName === "/" ? "home" : pathName?.replace("/", "");

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body className={`page-${className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
